name: Convert Obsidian Markdown to HTML and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Python (upgrade to 3.9 for obsidianhtml compatibility)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Updated from 3.8

      # Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf
          python -m pip install --upgrade pip  # Upgrade pip
          pip install obsidianhtml --verbose  # Install with verbose output

      # Copy custom Python script into the workflow environment
      - name: Copy Conversion Script
        run: |
          mkdir -p scripts
          echo "${{ secrets.CONVERSION_SCRIPT }}" > scripts/convert_md_to_html.py
          chmod +x scripts/convert_md_to_html.py

      # Run conversion script
      - name: Convert Markdown to HTML
        run: |
          python scripts/convert_md_to_html.py

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
