name: Convert Obsidian Markdown to HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set Git user identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Install Pandoc and Tar
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc tar
          
      - name: Create HTML template
        run: |
          cat > template.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>$title$</title>
          <style>
          body {
          max-width: 800px;
          margin: 40px auto;
          padding: 0 20px;
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
          line-height: 1.6;
          color: #333;
          }
          a { color: #0366d6; }
          h1, h2, h3 { line-height: 1.2; }
          img { max-width: 100%; }
          .breadcrumbs {
          margin-bottom: 20px;
          padding: 10px;
          background: #f6f8fa;
          border-radius: 4px;
          }
          </style>
          </head>
          <body>
          <div class="breadcrumbs">
          <a href="/">Home</a> / $breadcrumbs$
          </div>
          <h1>$title$</h1>
          $body$
          </body>
          </html>
          EOL
          
      - name: Convert all Markdown files to HTML
        run: |
          mkdir -p converted-html
          find . -type f -name "*.md" -not -path "./converted-html/*" -not -path "./.git/*" -exec sh -c '
          relpath="${1#./}"
          dirpath="$(dirname "$relpath")"
          filename="$(basename "$1")"
          basefilename="${filename%.*}"
          mkdir -p "converted-html/$dirpath"
          breadcrumbs=$(echo "$dirpath" | sed "s/\// \/ /g")
          pandoc "$1" \
          --from markdown \
          --to html \
          --standalone \
          --metadata title:"$basefilename" \
          --metadata breadcrumbs:"$breadcrumbs" \
          --output "converted-html/${relpath%.*}.html"
          
          # Rename "Welcome To My Notes!.html" to "index.html" after conversion
          if [ "$filename" = "Welcome To My Notes!.md" ]; then
            mv "converted-html/${relpath%.*}.html" "converted-html/index.html"
          fi
          ' {} \;
          
      - name: Upload all converted HTML files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: html-files
          path: converted-html/**/*.html  # This uploads all HTML files in the converted-html folder

      - name: Create and push HTML branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout --orphan html-branch
          git rm -rf .
          cp -r converted-html/* .
          git add .
          git commit -m "Update HTML files"
          git push -f origin html-branch:gh-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
