name: Convert Obsidian Markdown to HTML and Deploy to GitHub Pages
on:
 push:
   branches:
     - main  # Trigger the workflow on push to the main branch
 workflow_dispatch:  # Allow manual triggering of the workflow
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set Git user identity
       run: |
         git config --global user.name "TheMalevolentOne1"
         git config --global user.email "${{ secrets.EMAIL_ADDRESS }}"
     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '16'
     - name: Install dependencies
       run: |
         npm install marked fs path
     - name: Convert Obsidian Markdown to HTML
       run: |
         mkdir -p output
         node <<'EOF'
         const fs = require('fs');
         const path = require('path');
         const marked = require('marked');
         function convertMdToHtml(inputDir, outputDir) {
           const files = fs.readdirSync(inputDir);
           for (const file of files) {
             const fullPath = path.join(inputDir, file);
             const stats = fs.statSync(fullPath);
             if (stats.isDirectory()) {
               const newOutputDir = path.join(outputDir, file);
               fs.mkdirSync(newOutputDir, { recursive: true });
               convertMdToHtml(fullPath, newOutputDir);
             } else if (file.endsWith('.md')) {
               const markdown = fs.readFileSync(fullPath, 'utf8');
               const html = marked(markdown);
               const outputFilePath = path.join(outputDir, file.replace('.md', '.html'));
               fs.writeFileSync(outputFilePath, html);
             }
           }
         }
         convertMdToHtml('./', './output');
         EOF
     - name: Rename "Welcome To My Notes!.html" to index.html
       run: |
         if [ -f "output/Welcome To My Notes!.html" ]; then
           mv "output/Welcome To My Notes!.html" output/index.html
         fi
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v1
       with:
         path: output
 deploy:
   needs: build
   runs-on: ubuntu-latest
   permissions:
     pages: write
     id-token: write
   steps:
     - name: Deploy to GitHub Pages
       uses: actions/deploy-pages@v1
