name: Convert and Publish Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Markdown to HTML
      run: |
        find . -name "*.md" -exec sh -c 'pandoc "$0" -o "${0%.md}.html"' {} \;

    - name: Create pages-html branch
      run: git checkout -b pages-html

    - name: Add and commit changes
      run: |
        git add .
        git commit -m "Convert Markdown to HTML"

    - name: Push changes to pages-html branch
      uses: ad-m/github-push-action@v0.6
      with:
        branch: pages-html
        github_token: ${{ secrets.GITHUB_TOKEN }}
