name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up pandoc (for Markdown to HTML conversion)
      run: sudo apt-get install pandoc

    - name: Convert Markdown to HTML
      run: |
        # Find all markdown files in subdirectories and convert them to HTML
        find . -type f -name "*.md" | while read file; do
          echo "Converting $file to HTML"
          pandoc -f markdown "$file" -o "${file%.md}.html"
        done

    - name: Set up Git for pushing changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Create and push to gh-pages branch
      run: |
        # Create gh-pages branch if it doesn't exist
        git checkout --orphan gh-pages
        # Remove any files that were previously tracked
        git rm -rf .
        # Move all HTML files to the root of the repository (or any other desired path)
        find . -name "*.html" -exec mv {} ./ \;
        # Add the converted HTML files to the new branch
        git add .
        git commit -m "Deploy HTML files"
        git push --force origin gh-pages

    - name: Notify successful deployment
      run: echo "Deployment to GitHub Pages completed successfully!"
